# Numpy

In [1]:
import numpy as np
import time

In [2]:
arr= np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

(2, 3)
2
int64


In [4]:
py_list= list(range(1_00_000))
py_result= []
start_time= time.time()
for i in py_list:
    py_result.append(i+5)
end_time= time.time()
print('Python List Time:', end_time - start_time)

Python List Time: 0.047997474670410156


In [5]:
np_array= np.arange(1_000_000)
start_time= time.time()
np_result= np_array + 5
end_time= time.time()
print('Numpy Array Time:', end_time - start_time)

Numpy Array Time: 0.007998943328857422


In [6]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
print(np.diag([1, 2, 3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [8]:
np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [9]:
arr= np.array([1.2, 2.3, 4.5])
print(arr.astype(int))

[1 2 4]
